number = int(input("Input 5 digit number: "))
first, rem_1 = divmod(number, 10)
rem_1_str = str(rem_1)
second, rem_2 = divmod(first, 10)
rem_2_str = str(rem_2)
third, rem_3 = divmod(second, 10)
rem_3_str = str(rem_3)
fourth, rem_4 = divmod(third, 10)
rem_4_str = str(rem_4)
fifth, rem_5 = divmod(fourth, 10)
rem_5_str = str(rem_5)
result = rem_1_str + rem_2_str + rem_3_str + rem_4_str + rem_5_str
print(result)
